[tool.poetry]
name = "async_dns"
version = "2.0.0"
description = "Asynchronous DNS client and server"
authors = ["Gerald <gera2ld@live.com>"]
license = "MIT"
keywords = ["async", "dns", "asyncio"]
repository = "https://github.com/gera2ld/async_dns"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0,<9.0"
pytest-cov = ">=5.0,<6.0"
tox = ">=4.24,<5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
